version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.20.1
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9901:9901"
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml